### ISSUE TITLE
hard reset bootreason different while deepsleep and awake?

### ISSUE THREAD

**Issue by Zebble** [nodemcu/nodemcu-firmware#1059]
Not sure if this is an SDK limitation, a hardware limitation, or something in NodeMCU?

Noticed the following:

1)    If the device is in deep sleep, and I reset it, the bootreason is "wake from deep sleep".
2)    If the device is in deep sleep, and it wakes up itself, the bootreason is "wake from deep sleep".
3)    If I do a hard reset while it is out of deep sleep (ie. awake), the bootreason is "external reset".

Scenario 1 should really be "external reset" shouldn't it?

(FYI using latest dev w/SDK 1.5.1)

-zeb

**Comment by jmattsson** [comment]
In an ideal world (1) should indeed be external reset. Unfortunately for us, Espressif overlooked something or had something go wrong or maybe a change at the last minute with the hardware design. 

The in-ROM bootloader has an explicit code path^ for handling wake-from-deep-sleep. However, that code path doesn't reinitialise the SPI flash chip, and as such it fails to load the firmware on wake-up. Since the ROM bootloader can't be updated, they worked around that issue by hooking up the XPD_DCDC pin to the reset pin^^ on some modules. When the RTC wakeup timeout triggers, that line is pulsed, and by hooking it up to the reset you get, well, a reset rather than a proper wakeup, but at least the chip boots instead of getting stuck in the bootloader.

This is why on wake-up the SDK can't tell the difference between a deepsleep wakeup and an actual reset. It's frustrating, I know, but there's nothing we can do about if as far as I'm aware.

___
^) Based on my reading of the disassembly there-of.
^^) Here's how to [do it on an ESP-01](http://tim.jagenberg.info/2015/01/18/low-power-esp8266/)
