### ISSUE TITLE
tcp/ip net server problem

### ISSUE THREAD

**Issue by ocb00999** [nodemcu/nodemcu-firmware#1186]
I set up one ESP (nodeMCU) as AP and ran a tcp server on it.
I set up the other two ESPs in station mode and connected them to the AP. They have different IPs.
I then tried to connect the two ESPs as clients to the server (both on the same port). 
However, it doesn't seem that the server can handle the two connections simultaneously. I also cannot send messages from server to all connected clients.

**Comment by TerryE** [comment]
@ocb00999, this is a list of programming issues that you face, buy not necessarily a problem with the firmware, since others have managed to do all this successfully. Please read #719.  Without details on your firmware build and a specific test case demonstrating a clear firmware bug, we will have to close this issue.
