### ISSUE TITLE
ADC read() and readvdd33() switched?

### ISSUE THREAD

**Issue by skycoders** [nodemcu/nodemcu-firmware#1194]
I have read the old issues regarding ADC, but somehow it does not seem that this has really been solved. What I understood: readvdd33() did not work in the past and simply returned 65535; it can work now, but that byte in the esp init block must be changed.

What I observe: read() returns 65535 and readvdd33() returns the actual analog value from the ADC pin. I have a light sensor connected to it, and the returned values make total sense (between 0 and 4095).

My impression is that these calls are somehow switched internally so that you have to use the "wrong" one.

**Comment by jmattsson** [comment]
In order to correctly be able to read the system VDD the TOUT pin has to be left floating/unconnected. It sounds to me like you have your NodeMCU configured with [ESP_INIT_DATA_ENABLE_READVDD33](https://nodemcu.readthedocs.org/en/dev/en/modules/adc/) but still have the sensor hooked up. Please ensure init data byte 107 is set to ESP_INIT_DATA_ENABLE_READADC, at which point `adc.read()` will become available.
