### ISSUE TITLE
Heap problem HTTP GET with DHT11 and ESP01

### ISSUE THREAD

**Issue by amancinellib** [nodemcu/nodemcu-firmware#1270]
I'm using firmware 0.9.6 build 20150704 on ESP01 to send data over internet, but each tcp call the heap consumes about 500 bytes.

The code in the alarm is:

conn=net.createConnection(net.TCP, false) 
                    print("init:create="..node.heap())
                    conn:on(CONST_CONN_RECEIVE, function(conn, pl) 
                        print(pl)
                        pl=nil
                        collectgarbage();
                    end)
                    conn:on(CONST_CONN_CONNECTION, function(c)
                        c:send(HTTP_REQ_GET..jsonTemp..HTTP_HEADER)
                        end)
                    conn:on(CONST_CONN_SENT, function(conn) collectgarbage("collect") end)
                    conn:connect(SERVER_PORT,SERVER_IP)
                    print("init:finishconn="..node.heap())
                    conn=nil;t=nil;h=nil;
collectgarbage();

**Comment by dnc40085** [comment]
First of all, you should use a current build of NodeMCU which you can get from the [NodeMCU cloud builder](http://nodemcu-build.com/), the "dev" branch is the most current but isn't fully tested.

According to http://nodemcu-firmware.readthedocs.org/en/dev/en/support/, this sort of question is better asked on [esp8266.com](http://www.esp8266.com/viewforum.php?f=17) or stackoverflow.com, since the github issues section is for reporting firmware bugs.
