### ISSUE TITLE
mqtt:unsubscribe dumps

### ISSUE THREAD

**Issue by dvv** [nodemcu/nodemcu-firmware#1304]
```Lua
c = mqtt.Client("foo", 120)
c:connect("192.168.1.4", 1883, 0)
-- NB: http://nodemcu.readthedocs.io/en/dev/en/modules/mqtt/#syntax_7
c:unsubscribe("foo")
-- PANIC: unprotected error in call to Lua API (attempt to call a nil value)
```

**Comment by FrankX0** [comment]
You are unsubscribing from a topic you did not subscribe to first.
And you seem to mix the client name (foo) and a topic (foo).

**Comment by dvv** [comment]
I described the sequence on pretty valid calls which led to sudden reset.

**Comment by devsaurus** [comment]
Thanks for reporting @dvv.
It appears that the unsubscribe callback is triggered without being initialized earlier. `mud->cb_unsuback_ref` is only set when `c:unsubscribe()` [provides a callback function](https://github.com/nodemcu/nodemcu-firmware/blob/dev/app/modules/mqtt.c#L1283) - otherwise it remains uninitialized. I'll dig into a fix.

**Comment by pjsg** [comment]
Fix merged to dev
