### ISSUE TITLE
Reboot on setting pinmode of PIN11

### ISSUE THREAD

**Issue by TonyLianLong** [nodemcu/nodemcu-firmware#1306]
When I tried `gpio.mode(11,gpio.OUTPUT)`to set the mode of GPIO9, the chip reboot.
Maybe it's because of the watchdog since it waited for a while.

I tried GPIO 2 and it's fine,only GPIO10 and GPIO9 has that problem. There may lie a bug.

**Comment by devsaurus** [comment]
Happens for me as well when ESP's flash interface is configured for Q(uad)IO mode - GPIO9 and GPIO10 are used for SPI then. You need to configure D(ual)IO mode in order to make use of these additional GPIOs.

This can be done during flashing with esptool.py:
```
-- DIO mode:
esptool.py write_flash -fm dio -fs 32m 0x00000 ...

-- QIO mode (esptool's default):
esptool.py write_flash -fm qio -fs 32m 0x00000 ...
```

See also [What's the different between DIO and QIO mode?](http://nodemcu.readthedocs.io/en/dev/en/hardware-faq/#whats-the-different-between-dio-and-qio-mode).
