### ISSUE TITLE
Set serial baud rate

### ISSUE THREAD

**Issue by acdtrx** [nodemcu/nodemcu-firmware#15]
Hello,

It would be great to be able to set the serial baud rate higher than 9600bauds. I would like to use the module for audio streaming and that is why i'd need something like 115200bauds.

Is that possible?

Thank you,
Alex N

**Comment by Hassan-Ali-Hassan** [comment]
I'm sorry, but I seem to have a problem using uart.setup() ! I'm trying to change the baud rate to 115200 but with no avail. I write uart.setup(0, 115200, 8, 0, 1, 1), but then I get random characters in response and then the connection times out. Even using uart.setup()  for stopping the echo at default baud rate causes the nodemcu to time out as well.

I think it has to do with the firmware version that I'm using (nodemcu_float_0.9.6-dev_20150704), however, I tried to read the documentation on upgrading to the latest firmware and I couldn't do it (I find the necessary documentation lacking). Any help?

**Comment by marcelstoer** [comment]
> I tried to read the documentation on upgrading to the latest firmware and I couldn't do it (I find the necessary documentation lacking)

You're not serious, are you? The relevant hooks are right there on the homepage of this repository: https://github.com/nodemcu/nodemcu-firmware#documentation ("upgrading" = build & flash)

**Comment by Hassan-Ali-Hassan** [comment]
Yes I am serious :) I used the cloud build service to produce the firmware's bin file. I read the "Upgrading from SDK 0.9.x Firmware" section from which I quote:

> Download a recent SDK release, e.g. esp_iot_sdk_v1.4.0_15_09_18.zip or later and extract esp_init_data_default.bin from there. Use this file together with the new firmware during flashing

and also

> The address for esp_init_data_default.bin depends on the size of your module's flash. ESP-01, -03, -07 etc. with 512 kByte flash require 0x7c000. Init data goes to 0x3fc000 on an ESP-12E with 4 MByte flash.

so I did extract the specified file and since I'm using a LoLin nodemcu board running on ESP-12E, I flashed the firmware file (that I had got earlier from the cloud build service) to the address 0x00000, and esp_init_data_default.bin to 0x3FC000 as specified, and when I connected it to ESPlorer, it was not recognized.

I read the readme file in esp_iot_sdk_v1.4.0_15_09_18.zip, which stated that other files( blank.bin and eagle.irom0text.bin)  should also be flashed in addition to esp_init_data_default.bin to some addresses depending on which version of ESP I am using. Still with no avail. At some point I thought I made a mistake about the board (and hence the flashing addresses) so I tried different addresses and still it doesn't work.

**Comment by acdtrx** [comment]
Hello Hassan,

After the uart.setup() the ESP enters the configuration you specified for the serial so you'll have to reinitialise your serial connection with the parameters that you specified. It is normal to get random characters because your current serial connection no longer matches the parameters you have entered.

Hope this helps,
Alex N

**Comment by RenanKiindok** [comment]
Hello.
I always connect to nodeMCU using 115200 as baud rate. I saw everyone using 9600 but it doesn't work for me. I'm trying to send to ESP one blink led program but for every line of the programam return "ERROR" message. The communicating is working at 115200 because I can send AT commands and AT+RST (to reset by the ESPlorer), any way, when I press the reset button at board it is expect to show: "NodeMCU x.x.x build xxxxxxxxxx powered by Lua x.x.x" (the "x" is the version I'm expecting to show) but it returns a lot of random and wrong caracteres, is it related to baud rate?

**Comment by toninog** [comment]
@RenanKiindok I am having the same issue - did you find a resolution to this ?

**Comment by nickandrew** [comment]
This is a place for reporting bugs in NodeMCU; try a forum for asking this kind of question. Locking this issue.

**Comment by marcelstoer** [comment]
@toninog the details of what Nick was telling you are in #1010
