### ISSUE TITLE
More documentation on net.socket:hold() would be helpful

### ISSUE THREAD

**Issue by marcelstoer** [nodemcu/nodemcu-firmware#1593]
Triggered by a question at http://www.esp8266.com/viewtopic.php?f=23&t=12540 I found [`net.socket:hold()`](http://nodemcu.readthedocs.io/en/latest/en/modules/net/#netsockethold). I must agree that the documentation is everything but clear (to me at least). A few vital pieces of information seem to be missing.
That thread also links to a question posted to an Espressif forum by @nkolban asking for the same kind of clarification. He never got a reply.

Does one of the developers who contributed to the net module have more info?

**Comment by devsaurus** [comment]
I don't have further links, but used the hold and unhold functions in the [PCM network streaming example](https://github.com/nodemcu/nodemcu-firmware/blob/master/lua_examples/pcm/play_network.lua). They work "as expected" and notify the server to stop sending packets until further notice. It can stream several Mbytes of audio this way.
They're essential in cases when the data source (http server) is faster than the data sink (16k audio). RAM buffers would very quickly overflow otherwise.

**Comment by jmattsson** [comment]
Are they really essential? The TCP receive window would the throttling the flow regardless.

**Comment by devsaurus** [comment]
The TCP windowing would throttle, I agree. But I couldn't find any other solution on Lua level:

My code has to fetch the data when the receive cb fires and eventually buffer it before it's fed into the audio backend. That frees up net and TCP layer, so they happily accept more data from the sender and spill it through the next receive cb. I can't block the cb per se in order to propagate the full-stop downwards the networking stack.

In the end it's my Lua app that gets blown up in case I can't throttle the sender according to my bandwidth constraints.

**Comment by marcelstoer** [comment]
> They work "as expected" and notify the server to stop sending packets until further notice.
