### ISSUE TITLE
Add support for 'sent' callback in websocket client

### ISSUE THREAD

**Issue by mrk-its** [nodemcu/nodemcu-firmware#1603]
### Missing feature
websocket client should support 'sent' callback (like 'sent' callback in net module). Without that we drop packets when muliple send calls are issued in a row.

### Test code
```Lua
s=websocket.createClient();
s:on('connection', function()
  s:on('receive', function(s, msg) print(msg) end);
  s:send('msg1');
  s:send('msg2');
  s:send('msg3');
end)
s:connect('ws://echo.websocket.org/');
```

### Justification
We need this to reliably send data over websockets. Additionally this will unify a bit interface of net and websocket clients.

### Workarounds
Currently there are no workarounds for that

**Comment by luismfonseca** [comment]
Ideally, I think that you would be able to issue multiple send calls in a row and it wouldn't discard any send request.

It's very easy to add a `sent` hook in the LWIP/espconn layer, but the websocket implementation is also handling with the ping/pong/close. For pongs, the websocket just doesn't forward it to the application, but I'm not sure how to handle the pings because you'd need to store somewhere that the next `sent` is to be discarded and not forwarded to the application...

Perhaps this could just be a counter `internal_sent_requests` that gets increased whenever an internal frame is sent, and decreased when the `sent` callback is triggered. Only notify the application code if it's `0`...
