### ISSUE TITLE
Where can I find the latest firmware ?

### ISSUE THREAD

**Issue by NuwanJ** [nodemcu/nodemcu-firmware#1641]
Please anyone can help me to find any pre build nodeMcu firmware ? Now I can't see any bin file in github repository.

**Comment by lszeremeta** [comment]
There is no official pre-build firmware. Follow [this instructions](https://nodemcu.readthedocs.io/en/master/en/build/) to build your own firmware. I recommend you use the [online service](https://nodemcu-build.com/) to do this. Building packages by yourself is better because you can specify what you need in your firmware.

**Comment by marcelstoer** [comment]
https://github.com/nodemcu/nodemcu-firmware#releases
