### ISSUE TITLE
"Chinese nodeMCU API"  should be updated!

### ISSUE THREAD

**Issue by bakabird** [nodemcu/nodemcu-firmware#1732]
https://github.com/nodemcu/nodemcu-firmware/wiki/nodemcu_api_cn#tmrdelay 

too old to use.

**Comment by marcelstoer** [comment]
It says here https://github.com/nodemcu/nodemcu-firmware/wiki#outdated-and-sparse-documentation and here http://nodemcu.readthedocs.io/en/master/ that the firmware team only maintains the English version (due to both time and language constraints).

However, we'd be happy to accept PRs for translated documentation. Our doc system is already prepared for multi-language.

I assume you speak Chinese. Feel free to add a comment at the top of https://github.com/nodemcu/nodemcu-firmware/wiki/nodemcu_api_cn.

Also take note of #1010.
