### ISSUE TITLE
ESP32: uart1/uart2 support

### ISSUE THREAD

**Issue by zelll** [nodemcu/nodemcu-firmware#1960]
I'm adding uart1/uart2 support to uart module. I noticed there had been some code for more uart(s) in `platform.c` and `platform.h` . So I tried to do it in the way expected...

I added `start()` and `stop()` functions, and changed signature of `on()` and `setup()`. Docs is updated [here](https://github.com/zelll/nodemcu-firmware/blob/dev-esp32-uart12/docs/en/modules/uart.md).
> uart.on(**[id],** method, [number/end_char], [function], [run_input])
> uart.setup(id, baud, databits, parity, stopbits, **echo_or_pins**)

@jmattsson Can you review it? 
https://github.com/zelll/nodemcu-firmware/tree/dev-esp32-uart12

**Comment by jmattsson** [comment]
This is looking promising!

The docs seem to make the assumption that the console is always on UART 0. I don't know if that's necessarily true going forward?

I dropped a few comments in the branch you linked. Mostly small things. The one more conceptual question is how this will play with the `/dev/uartX` files/streams the IDF provides through the VFS. I haven't looked at how that works under the hood, but we should do something sane with regard to it. Possibly implement these uarts on top of that interface, if the `uart_write_bytes()` doesn't already play nice with it? @devsaurus have you poked around in this area lately?

**Comment by devsaurus** [comment]
My understanding was that the `uart` module operates on the UART hardware/driver combo and is agnostic of the /dev/uartx streams. This appears to work interestingly well for stdout so far (VFS and `uart` module write to the UART driver via `uart_tx_char()`). But if someone ever tries to read from stdin then both might step on each others toes (VFS code directly accesses the UART HW regs).

Settling our `uart` module on top of the VFS stream abstraction would not be an option since there are no means to configure the stream in terms of terminal settings (ioctl and friends).

**Comment by jmattsson** [comment]
Cool, sounds like the current approach is the sane way then. Thanks for the input!

**Comment by zelll** [comment]
Some new ideas.
1. `uart.start(1)` takes more than 5 KB memory. I want to let `start()` return 0 or error code (returns `void` now). 
2. Make `uart.write()` returning _wrote bytes_, so lua can control data flow. 

seems ok?
