### ISSUE TITLE
http.post can't disconnected

### ISSUE THREAD

**Issue by andriwarda** [nodemcu/nodemcu-firmware#1990]
I try to send post request using http.post. Here my code:
```lua
function func_http()  
   http.post('http://192.168.56.101:3000/jwt',
  'Content-Type: application/x-www-form-urlencoded\r\n',
  'Connection: keep-alive\r\nAccept: */*\r\n',
  '{"username":"FILKOM_1", "password":"rahasia"}',
  function(code, data)
    if (code < 0) then
      print("HTTP request failed")
    else
      print(code, data)
      token = data
    end
  end)
end
```

If success, i will get a token. But when i run my code i have error
```
HTTP client: Connection timeout
HTTP client: Disconnected with error: -11
HTTP client: Connection timeout
```

**Comment by marcelstoer** [comment]
I'm going to close this as there's no evidence (yet) there's anything wrong with the firmware. We can't even test ourselves because http://192.168.56.101:3000 is a private resource (try http://putsreq.com/ for public example). What is definitely wrong is that you use too many parameters for `http.post`, see https://nodemcu.readthedocs.io/en/latest/en/modules/http/#httppost
