### ISSUE TITLE
[FR] Lua's `debug` option

### ISSUE THREAD

**Issue by ildar** [nodemcu/nodemcu-firmware#2436]
### Missing feature
`README.md` says:
> Lua 5.1.4 (without debug, os modules)

I wonder if it's (not) hard to get **Lua's debug** back as an opt-in feature.

### Justification
There are nice Lua debug tools relying on this Lua interpreter's feature. I want to use it.

**Comment by marcelstoer** [comment]
It would be nice if it were just like debugging a local Lua script, indeed. However, remote debugging (i.e. over TTL serial) a microcontroller is quite a different world. I personally never tried but there's a dedicated module for that https://nodemcu.readthedocs.io/en/master/en/modules/gdbstub/

**Comment by TerryE** [comment]
@ildar,  I also think that the ability to enable some or all of the debug features seems like a nice-to-have. However, it is a mistake to believe that these are a full debugger, they are more the in-RTS elements or a debug stub that could enable a IDE to implement a Lua debugging capability.  Four main issues here:
1.  There AFAIK, there is no defacto preferred Lua debugger from the [options available](http://lua-users.org/wiki/DebuggingLuaCode).  Have you any experience of these?
2.  Enabling debugging materially increases the RAM footprint of the code, so until the introduction of LFS, this would be impractical.  Note that my LCD patch enabled a intermediate option between no debug and full debug, that is retaining a compressed line number vector (~1 byte per Lua source line, rather than 4-byte pre Lua VM instruction) so that errors produce meaningful line number tracebacks.
3. The NodeMCU RTS implements an asynchronous execution model that is very similar to Javascript's **node.js** environment.  Interactive debugging is intrinsically a synchronous activity with a developer in the loop.  As with **node.js** human interaction in this way breaks the application.
4.  Any solution here would involve a _lot_ of development effort. 

So this isn't going to happen any time soon, as the expert developer resources here are limited (me when I have time) and I have other more important priorities.  Sorry

**Comment by ildar** [comment]
Guys, thanks for your answers, especially @Terry, thanks a lot for the
detailed overview.
I just started with NodeMCU so need some time to look around. Need to bring
up both ESP8266 and ESP32.

Regarding the Lua debugger, it's
> [MobDebug] - remote Lua debugger using sockets (based on RemDebug);
integrates with [ZeroBrane Studio Lua IDE]

- very nice thing to play with.
