### ISSUE TITLE
Interrupts priority?

### ISSUE THREAD

**Issue by raz123** [nodemcu/nodemcu-firmware#253]
Could we get information about how NodeMCU handles a GPIO interrupt if it occurs while the CPU is running inside a Timer interrupt, and the opposite?

**Comment by nodemcu** [comment]
gpio interrupt and timer interrupt in nodemcu is a api wrap of esp8266 sdk.
I haven't find any priority info from sdk doc.
but, on the other hand, lua handle all this interrupt same as a "software" interrupt.
so when one hardware interrupt occurs, it just call some lua api from c code. 
then another hardware interrupt come, calls some other lua api. AFTER the previous done,
because it's single thread. 
so I think/guess, maybe the second interrupt will be missed.
