### ISSUE TITLE
gzip support (inflate)

### ISSUE THREAD

**Issue by pjsg** [nodemcu/nodemcu-firmware#2598]
### Missing feature
No way to expand a gzip http response....

### Justification
The api.darksky.net site only supports compressed responses. (Argh!)

### Workarounds
Nope.

### Approach
I was thinking of adding a `file.gunzip(<sourcefile>, <destfile>)` api that would read from the sourcefile and decompress into destfile. The code that was added in `uzlib` makes it possible to decompress with a fairly small footprint. Using a file as the output means that we can expand to sizes that are much larger than memory. 

I'd like to have the gzip interface as well, but that would need more work in uzlib_deflate....

Thoughts?

**Comment by nwf** [comment]
Rather than using SPIFFS and burning an erase cycle, it may be better to have a streaming interface to the decompressed contents?  Users can write to SPIFFS if they wish in the callback.

**Comment by pjsg** [comment]
The issue with that is that you need to be able to look back in the output
stream when decompressing. When the entire output stream doesn't fit in
memory you are sunk. I don't like having to use flash to store the data,
but I don't see another way of doing it.

The other alternative is to have a proxy somewhere that does the
decompression.

**Comment by nwf** [comment]
I think you only need to have the current compressed chunk for gzip, and if memory serves you can do even better by only keeping the chunk's *dictionary* and streaming through the remainder of the chunk.  It's probably a little tricky, but could be worth pursuing.

Could you make `file.gunzip` a streaming API while it's decompressing from SPIFFS?  If it needs to seek around, that should be possible.  That at least limits the "fetch compressed chunk from server, decompress" to one mandatory SPIFFS erase cycle, not two (just compressed stream, not compressed stream and uncompressed stream), and we can address the one later.

**Comment by pjsg** [comment]
Actually, I think that you only need the input *stream* and the entire
output -- thus you could decompress in one cycle -- by writing into the
decompressor and have it write to SPIFFS (but it needs to be able to fetch
arbitrary pieces of previously emitted output).

**Comment by TerryE** [comment]
@pjsg, Philip the streaming code exists in the `lua/lflash.c` module.  The issue is that it needs an expansion lookback which is the size of `min(dictionarySize, streamsize)`.  Unfortunately the GZIP standard itself specifies a dictionary of 32Kb which when added to input / output buffers etc. will crater an ESP8266 with a RAM exhaustion error. That's why I decided to tweak the  `uzlib` code to use a 16Kb dictionary.  This only degrades the compression performance by a few percent, but makes the inflation doable in the ESP8266 within an LFS-based application.  The streaming implementation allocates the buffers based on the input file size.  

Clearly in the use case where you are using deflate / inflate for smallish records -- say json.gz strings over TCP, then the maximum dictionary is the compressed record size and thus you could easily do the entire decode in memory if your compressed json buffers where less than 8K, say.  

As I comment somewhere in the uzlib / lflash.c code, this is on my low priority TODO list. but feel free to look at the code and offer your own module wrapper.  I will offer any review support that you need.
