### ISSUE TITLE
Building documentation locally

### ISSUE THREAD

**Issue by cwrseck** [nodemcu/nodemcu-firmware#2645]
8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
Documentation builds locally with "mkdocs build"

### Actual behaviour

Building the docs for the nodemcu-221-20181207 release locally presents
several problems; I'm not sure which are bugs and which are features.

Ubuntu 16.04 and 18.04 use mkdocs 0.16.3 as the default version. "mkdocs build"
then produces the error message:

cwr@tanner:/tmp/nodemcu$ mkdocs build
ERROR   -  Config value: 'theme'. Error: Unrecognised theme '{u'name': u'readthedocs'}'. The available installed themes are: readthedocs, mkdocs 

Aborted with 1 Configuration Errors!
cwr@tanner:/tmp/nodemcu$ 

I couldn't find a way to acess the correct theme, under python 2.x or 3.x,
so I updated with pip to the current mkdocs 1.0.4. This produced:

cwr@tanner:/tmp/nodemcu$ mkdocs build
WARNING -  Config value: 'pages'. Warning: The 'pages' configuration option has been deprecated and will be removed in a future release of MkDocs. Use 'nav' instead. 

Aborted with 1 Configuration Warnings in 'strict' mode!
cwr@tanner:/tmp/nodemcu$ 

When mkdocs.yml was updated accordingly it produced 82 warnings of the form:
WARNING -  Documentation file 'en/modules/adc.md' contains a link to '../app/modules/adc.c' which is not found in the documentation files. 
...
Exited with 82 warnings in strict mode.

It looks as if mkdocs can't handle triple links of the form "../../..";
once the app directory was linked into the docs/en directory, and the md files
edited appropriately, only 12 warnings remained, and I ignored them.

The doc linkages still needed a fair amount of cleaning up with sed, but they
were finally actually readable on a local machine.

C W Rose

**Comment by galjonsfigur** [comment]
I was rebuilding documentation for some modules and the version I'm using is mkdocs 0.17.5 from pip. Newer versions have some problems - see #2600. I was looking around to find a solution and symlinking both app and lua_modules folder would be needed for it to work. There is [metadata extension](https://squidfunk.github.io/mkdocs-material/extensions/metadata/) but that would work/look different than current table with author, date and source file location + it would require changes in the theme files so it's more complicated solution.

@cwrseck If you want I can do it and send PR but If you want to send your changes it would be good too I think. But before it - I don't know if this could break documentation hosted on ReadTheDocs. This needs to be checked.

**Comment by marcelstoer** [comment]
It's unfortunate that we don't have total freedom wrt the MkDocs version we use. As we're building and hosting on http://readthedocs.org we have to stick with what they currently support. We do have `rtd-requirements.txt` in the repository which we can use to define our own version they should use for building but that only helps if they integrate well with the version we declare. That's the reason all entries in that file are currently commented out.

In the `dev` branch we already use `strict: false` due to the unreachable source code references: https://github.com/nodemcu/nodemcu-firmware/blob/dev/mkdocs.yml#L7. See https://github.com/mkdocs/mkdocs/issues/1619 for further details.

**Comment by cwrseck** [comment]
Thanks; #1619 is a very useful reference - I couldn't find it with a Google search.  I'm a bit surprised
that  the permitted mkdocs 0.16.3 throws an error message, and I'd dearly like to know how to fix it,
but I really can't see any urgency.  Perhaps just keep an eye on the problem as the docs are updated.

(BTW, the docs are very good indeed; it's just that I work offline a lot, and tend to rely on them
being available.)

C W Rose

**Comment by marcelstoer** [comment]
I use mkdocs 1.0.x locally (as I need a recent version for other projects) and I ignore the warnings for now.

@galjonsfigur how about a PR for a `.sh` that creates the necessary symlinks and starts `mkdocs`?

**Comment by galjonsfigur** [comment]
@marcelstoer That might be a good idea but it would work only for *nix systems. I will check how ReadTheDocs would handle symbolic links in repository - in git symlinks work fine and on windows git would just produce text file with path instead of link itself. I will try both options, see which works better and send a PR.
