### ISSUE TITLE
Unaligned load/store exception in luaR_findentry

### ISSUE THREAD

**Issue by pjsg** [nodemcu/nodemcu-firmware#2701]
### Expected behavior

it doesn't trap!

### Actual behavior

It traps

### Test code
With LFS enabled and a flash image loaded with @TerryE _init.lua loaded and initialized and with the string "/data" in the LFS

```Lua
require (string.sub("/data", 2, -1))
```
### NodeMCU version
Current dev

```
  c0:   82cc            bnez.n  a2, cc <luaR_findentry+0xb0>
  c2:   1148            l32i.n  a4, a1, 4
  c4:   0a4416          beqz    a4, 16c <luaR_findentry+0x150>
  c7:   0459            s32i.n  a5, a4, 0
  c9:   0027c6          j       16c <luaR_findentry+0x150>
  cc:   0cb8            l32i.n  a11, a12, 0      <===== this blows up
  ce:   869c            beqz.n  a6, ea <luaR_findentry+0xce>
  d0:   3628            l32i.n  a2, a6, 12
  d2:   fa7c            movi.n  a10, -1
  d4:   1432f6          bgeui   a2, 3, ec <luaR_findentry+0xd0>
```

We don't have an unaligned handler for l32i (only for 8 and 16).

**Comment by TerryE** [comment]
@pjsg Philip, I'll take a look, but I might need the code base for a test case.  I will see if I can recreate it just from the info posted.

**Comment by pjsg** [comment]
I just diagnosed the issue -- I updated the original message -- it is a lack of a l32ui unaligned handler.

**Comment by TerryE** [comment]
That's because we shouldn't be doing any unaligned 32-bit accesses. If we are then it's a bug, because all of our 32 and 64-bit fields would be word-aligned.

**Comment by pjsg** [comment]
The luaR_findentry code assumes that strings are 32 bit aligned ...

**Comment by TerryE** [comment]
I know that. Are you compiling with `-Os`?  That would explain the error, but even in this case, we should still tweak the macros to force this as `-Os` should only result in a performance hit and not an error.

**Comment by pjsg** [comment]
No. -O2. The issue is (I think) that the string.sub can return an unaligned
string if you are requesting the tail end of a read-only string.

**Comment by TerryE** [comment]
Thanks Philip, I'll look, and I think that you might be close to the nub. Standard Lua creates a new TString with an aligned copy of the string. The issue is that we are using the eLua patch which uses a reference if the original string is in Flash. I'll push out a fix tomorrow.

**Comment by TerryE** [comment]
OK, `str_sub()` does a `lua_pushlstring(L, s+start-1, end-start+1)` in other words if the string is in ROM then, this passes the (not necessarily word aligned) start address and length.  This is just a parameter checking wrapper for a call to `luaS_newlstr(L, s, len)` which calls `newlstr(L, str, l, h, TRUE)` if this is a new TString where the string is in Flash.  With the **eLua** patch, the TString uses a reference to the (not necessarily word aligned) start address and sets the `marked` READONLY bit to flag this use of a reference.

The issue is that the ROTable scan starting at [lrotable.c:L104](/nodemcu/nodemcu-firmware/blob/dev/app/lua/lrotable.c#L104) has been highly optimised to do one flash word read per table entry and the assignment at L104 assumes that strkey is word aligned.  Oops.  The simplest work around that keeps this fast scan is to use `c_memcpy()` for this assignment as this ROM version is optimised for word aligned copies but still handles non-aligned copies from ROM correctly.

**Comment by TerryE** [comment]
`_VERSION` is another string using a RO indirection so `require ('_VERSION'):sub(3,-1)` also does the required crash.  The `c_memcpy` change fixes this.  I was sloppy and just used an SDK 3.0 version first to test this bug, but just couldn't get it to raise the exception.  Guess what the SDK 3.0 uses an Espressif version of the exception handler and this _does_ handle unaligned 32bit errors.  No crash here.  Still, it is worth putting in this one liner.
