### ISSUE TITLE
table.concat calc error when \0 in string

### ISSUE THREAD

**Issue by feilongfl** [nodemcu/nodemcu-firmware#2775]
### Expected behavior
```Lua
=table.concat({0x41,0x42,0x00,0x44,"Hell\0o",0x45})
6566068Hell(\0here)o69
```

### Actual behavior
```Lua
=table.concat({0x41,0x42,0x00,0x44,"Hell\0o",0x45})
6566068Hell
```

### Test code
```Lua
table.concat({0x41,0x42,0x00,0x44,"Hell\0o",0x45})
```
### NodeMCU version
NodeMCU 3.0.0.0 build unspecified powered by Lua 5.1.4 on SDK 3.0.1-dev(fce080e)

### Hardware
esp12 (maybe)(I bought it from https://detail.tmall.com/item.htm?id=535433433157)

**Comment by TerryE** [comment]
Thank you @feilongfl. This is a bug, but if you try your test case on PC Lua 5.1.x then you will see that this also manifests this behaviour.  This is a core Lua bug and not a NodeMCU one. I think that the correct fix is to wait until we deploy Lua 5.3 rather than diverge further from for Lua behaviour.
