### ISSUE TITLE
Implementing Web Sockets

### ISSUE THREAD

**Issue by samehhady** [nodemcu/nodemcu-firmware#30]
Hi Zeroday,

You think its possible to implement web sockets on ESP?

Think of it as we will be able to control all ESPs using a cloud server & there will be 2 way communication between all ESPs and the server!

Also this can provide a cloud based flashing tool for ESP, we will be able to flash the ESPs from anywhere!

**Comment by kireevco** [comment]
I used rabbitmq with web-stomp and mqtt to connect nodemcu.
I would rather have mqtt working more stable on the ESP8266.

**Comment by dvv** [comment]
There's also a good and lightweight https://developer.mozilla.org/en-US/docs/Web/API/EventSource

**Comment by kireevco** [comment]
Thanks. mosquitto / rabbitmq has websocket support. I use rabbitmq on a raspberry pi as a central hub, works great.

**Comment by urmilparikh** [comment]
@samehhady, it will be nice if you can share your lua or js code to implement Websocket over TCP connection.

I'm planning to do so, can leverage on your work.

Thanks!

**Comment by creationix** [comment]
Websocket is a little heavy, but I think it can be done.  I tried porting my luvit websocket library but it used too much ram.  The protocol itself is pretty simple.  When I get a chance I'll write a pure lua websocket server so that an html5 based app can talk directly to the nodemcu.

**Comment by pastukhov** [comment]
The main problem is md5 and sha1 algorithms, as i see.

**Comment by creationix** [comment]
Those can also be implemented in lua, I've done it a few times before in JS.  Though I do wonder how much memory that would use.

**Comment by creationix** [comment]
@pastukhov There is no MD5 is websocket, but you do need SHA1 and Base64 encoding.  Here is a sha1 function I just wrote using the `bit.*` library that should work.
https://gist.github.com/creationix/7ce3796e65b66549c4b0

**Comment by pastukhov** [comment]
I'm getting 
```lua
> dofile('testsha1.lua')
string length overflow
```

**Comment by creationix** [comment]
@pastukhov You probably don't want to run all the unit tests on the nodemcu.  One is calculating the sha1 of a string containing 1,000,000 "a"s long.  The values that will be used in websocket handshake are under 100 characters long.

**Comment by ikaras** [comment]
Hi, all!
I tried to resolve issue with websocket client for nodemcu: https://github.com/ikaras/nodemcu-websocket-client
Take a look and be free to use it.

**Comment by creationix** [comment]
Now that we have sha1 and friends in the core and a lot more free ram than when I initially started this, making a websocket server and/or client is quite feasible. 

See also my past experiments in this area:

- https://gist.github.com/creationix/079e11345249525c7e2e
- https://github.com/creationix/nodemcu-webide

I'm especially excited about websocket server since it means that browsers can directly talk to the mcu without any proxy in between.  You can still host the bulk of the web ide (js/css/html) in the cloud and use cache-manifest or service workers to make it work when the laptop is offline.

I'm currently working on a new VM for esp chips that should use less ram than lua. It will have websocket built-in.  The basic workflow will be browser based so that any device on the same wifi network as the mcu can program it.  There will be a repl in the browser as well as a code editor.  My compiler from the high-level language down to the bytecode running in the vm will be implemented in JS so the mcu doesn't have the overhead of a compiler.

**Comment by ikaras** [comment]
Hi @creationix.
That's great.
I saw your websocket server - it's great! and as I'm noob in Lua and in nodemcu/esp8266 I used your code to encode/decode messages and it works perfect. A little bit later I'll add notes about it to readme.

**Comment by ikaras** [comment]
[
