### ISSUE TITLE
ESP32: Docker build fails on Windows

### ISSUE THREAD

**Issue by artem-dudarev** [nodemcu/nodemcu-firmware#3001]
When I run the following command:
```
docker run --rm -it -v D:/ESP32/nodemcu-firmware:/opt/nodemcu-firmware marcelstoer/nodemcu-build build
```
it fails with the following message:
```
sed: -e expression #1, char 99: unknown option to `s'
```
![image](https://user-images.githubusercontent.com/8775253/71755259-6ef6ea80-2e92-11ea-989e-1169d6bb858c.png)

Windows 10 Enterprise 1909 x64
Docker desktop: 2.1.0.5 (40693)
Git branch: dev-esp32
Latest commit: bfd22591

**Comment by marcelstoer** [comment]
Belongs here https://github.com/marcelstoer/docker-nodemcu-build but GitHub doesn't allow moving across account boundaries -> closing

I'm pretty sure this was fixed with https://github.com/marcelstoer/docker-nodemcu-build/commit/8350cbdf4412021dc1a2307cebed05d10340fdcd. You might need to update your image by running `docker pull marcelstoer/nodemcu-build`.
