### ISSUE TITLE
writing to socket from functions does not work

### ISSUE THREAD

**Issue by Na2l** [nodemcu/nodemcu-firmware#32]
Hi,
 this works:
sk=net.createConnection(net.TCP, 0)
sk:on("receive", function(sck, c) print(c) end )
sk:connect(5555,"192.168.1.8")
sk:send("HELLO")
sk:close()
print("sent to server")

================================
but this does not:
================================
function test()
sk=net.createConnection(net.TCP, 0)
sk:on("receive", function(sck, c) print(c) end )
sk:connect(5555,"192.168.1.8")
sk:send("HELLO")
sk:close()
print("sent to server")
end

**Comment by nodemcu** [comment]
I have test the code above.
it IS because of closing connection too fast.

**Comment by doorlockproject** [comment]
I have this same issue, but this solution does not work for me. In fact, the sent event is never even triggered.

Works:
```lua
    conn=net.createConnection(net.TCP, 0)
    conn:on("receive", handleHTTP)
    conn:connect(80,"google.com")
    conn:send("GET / HTTP/1.1\r\nHost: google.com\r\nAccept: */*\r\n\r\n")  
```

Doesn't work:

```lua
function hitServer()
    conn=net.createConnection(net.TCP, 0)
    conn:on("receive", handleHTTP)
    conn:connect(80,"google.com")
    conn:send("GET / HTTP/1.1\r\nHost: google.com\r\nAccept: */*\r\n\r\n")  
end
hitServer()

```

**Comment by TerryE** [comment]
@nodemcu, we are going to continue to get these false issue reports until somebody documents exactly how the event system interplays with the inline Lua execution in a plain and understandable programming guide for new-to-ESP8266 developers.
@doorlockproject, The way that the ESP supplied SDK works means that this Lua implementation is event driven as a lot of the system calls are asynchronous, so for example `conn:connect()` initiates the process of connecting to google.com.  It does not wait for its completion. The following `conn:send()` instruction in your example starts immediately and before the connection has had time to complete, so there is no guarantee that this method of coding will actually work.  Clearly, we on an edge here because it works in some varieties and not it others. If you do this by the approach given in  `examples/fragment.lua`, then you will find that it works properly :smiley: 

```Lua
sk=net.createConnection(net.TCP, 0) 
sk:on("receive", function(sck, c) print(c) end )
sk:on("connection", function(sck) 
    sck:send("GET / HTTPS/1.1\r\nHost: www.google.com.hk\r\nConnection: keep-alive\r\nAccept: */*\r\n\r\n") 
  end) 
sk:connect(80,"google.com")

**Comment by doorlockproject** [comment]
That works perfectly, thank you.

**Comment by ashwinipatil123** [comment]
can I go for uploading a file containing real time data from client to server. If yes then how?
Well, I can establish client server communication successfully using above given code.

**Comment by TerryE** [comment]
@ashwinipatil123, please ask developer Qs on a developer forum as per my last reply to you.

**Comment by charlythegood** [comment]
Terrye Hello , I would like to ask if you can record real-time reading a sensor nodemcu a mysql database .
I have managed to record individual data, but I have problems running a FOR or WHILE .
Thank you.

**Comment by TerryE** [comment]
@charlythegood, This is one for an application developers forum rather than on this list, so I won't give a full reply.  The issue that you have is that you have a memory leak in your socket handling.  The library has known issues which can result in such leaks depending on how you close out each request. 

One simple approach if you can't track down and eliminate the leak is if you can reply to 30 requests safely, then simply restart your ESP (say 2 seconds) after replying to the 30 request.

**Comment by MrAda** [comment]
handleHTTP, what is this?

**Comment by TerryE** [comment]
@MrAda Chris, This question is one for resolution by code inspection or an application developers forum rather than one for this list.
