### ISSUE TITLE
Wifi connection lost..... No re-connection still no fix

### ISSUE THREAD

**Issue by chathurangawijetunge** [nodemcu/nodemcu-firmware#3271]
**why (Wifi connection lost..... No reconnection #3208) was close with out a fix?????????**

NodeMCU 3.0.0.0
branch: dev
commit: a0d2705
release: 3.0-master_20200610 +25
release DTS: 202009031150
SSL: false
build type: integer
LFS: 0x40000 bytes total capacity
modules: file,gpio,mqtt,net,node,rtctime,sntp,tmr,uart,wifi
build 2020-09-04 17:10 powered by Lua 5.1.4 on SDK 3.0.1-dev(fce080e)

**I am getting the same error..... wifi will not auto reconnect.
I am using esp-12 with 4M and since im on windows i use PyFlasher with the option 'yes,wipe all data' enable to flash the freeware. but no luck.**

**i tried with esptool.py erase_flash but no luck after some time i get error 201 [wifi.eventmon.reason.NO_AP_FOUND]
but with wifi.sta.getconfig() i get valid SSID , PWD and BSSID.... but no re connection even with node.restart() until power cycle or hard reset.**

**this is a major issue guys.......**

**Comment by nwf** [comment]
It was closed because we apparently believed we had it fixed.  Your repeated posting of multiple redundant things to our bugtracker is **very obnoxious**.  I'm sorry it's not working for you, but understand that this is **a hobby** for most of us, and so you should expect hobby-grade support and reliability of the entire project by default; if you need actual support, I think your answers are A) get into the firmware source and debug it yourself (which you, AFAICT, so far have not attempted), B) pay someone to do that, C) find a workaround (e.g., hard reset via looped GPIO pin), or D) find some other substrate than the NodeMCU project and/or ESP8266.

In any case, I have reopened #3208, which contains the same text as this bug report.
