### ISSUE TITLE
nodemcu-build doesn't work

### ISSUE THREAD

**Issue by azureblue** [nodemcu/nodemcu-firmware#3391]
Not getting any emails from https://nodemcu-build.com after triggering builds. 
Tried different emails, days.

Yes, I checked spam folder.

@marcelstoer

**Comment by marcelstoer** [comment]
Sorry for the trouble. 

This came completely out of the blue. The build sends me an email if things go south but it's been very quiet lately. I checked the logs, all good as well. Then I checked the build pipeline on travis-ci.org because Travis does the heavy lifting...not a pretty sight. For whatever reason their NodeMCU build queue is full and the backlog huge. No idea why. 

As an immediate measure I switched from their .org to .com as the former is soon shutting down soon. Hence, I would have had to transition at some point anyway.

They transitioned some of the build queue with it but unfortunately they're processing it the LIFO-way rather than FIFO. Again, no idea why; doesn't make sense to me.

If Travis continues to cause trouble I might have to bite the bullet and move everything to GitHub actions. @HHHartmann I feel you're quite happy with their offering?

**Comment by azureblue** [comment]
Ok :). Thanks for the answer. :+1:

**Comment by marcelstoer** [comment]
Oh, and in case it wasn't obvious: since they use LIFO you might be able to jump the queue if you just trigger another build 😜

**Comment by azureblue** [comment]
Ok, let's test that statement then! :)

**Comment by azureblue** [comment]
The build is indeed running :).

PS but why would they use LIFO? 😲
