### ISSUE TITLE
Check restart reason

### ISSUE THREAD

**Issue by vudangngoc** [nodemcu/nodemcu-firmware#442]
I think it's good to know why NodeMCU restart, this information will help developer handle behavior of NodeMCU more easily, avoid causes make NodeMCU restart and improve reliable of ESP.

**Comment by dperlman** [comment]
My understanding is that nodeMCU restarts because the watchdog timer times out. This means either that user code entered a blocking loop which didn't allow the timer to reset; or else the firmware was rendered non-functional by memory corruption resulting from heap overflow. In either case, there's no practical way for the firmware to track the cause of its own failure. However, if you watch the serial console output, there is almost always an error message before the restart and you can figure out what happened from that.

**Comment by vudangngoc** [comment]
Can we determine restart cause is power cutting or watchdog time out?

**Comment by cal101** [comment]
Moin,

watchdog resets will print "wdt reset".

Cal

**Comment by drv53b6** [comment]
node.restart(restart_code)
print(node.rcode())
or
print(rcode) rcode=nil

**Comment by TerryE** [comment]
@drv53b6 -- except that `node.restart()` doesn't take any parameters and the **node** library doesn't contain a  `node.rcode()` method.

**Comment by drv53b6** [comment]
@TerryE must do it, it will be very useful

**Comment by vudangngoc** [comment]
@cal101 : where it print "wdt reset"? any news about this issue?

**Comment by jmattsson** [comment]
There is also a ROM function called rtc_get_reset_reason() which returns the reset reason. 4 is the code for wdt reset, 3 for reset via the reset pin. I can't remember what the code for a cold boot is off the top of my head.

**Comment by vudangngoc** [comment]
@jmattsson : could you please give me a piece of example code?

**Comment by MarsTechHAN** [comment]
@vudangngoc When ESP8266 restart it will print information at 74880bps

**Comment by Air000** [comment]
@jmattsson where to find the definitions of rtc_get_reset_reason()'s return value?

**Comment by jorgempy** [comment]
this should be closed, as #512 has been merged. also it should be documented somewhere.
