### ISSUE TITLE
filenames with "\r\n" is hide files on filesystem

### ISSUE THREAD

**Issue by znsoft** [nodemcu/nodemcu-firmware#484]
dev096:
if filesystem have many files (9 for example like "init.lua, a, c, d, e" .. e.t.c) then
```lua
file.open("b\r\n","w")
file.writeline("test")
file.close()
```
 file.list() hide init.lua, c d e and many other files, but they are running by dofile() and not opens by file.open(), ESPlorer stop when try get filelist

**Comment by TerryE** [comment]
Thank-you for this, but the bug is in **ESPlorer** not in nodeMCU.  noneMCU is pretty tolerant of characters inside filenames and ESPlorer doesn't follow the same rules (for example you can embed `/` in nodeMCU filenames but ESPlorer strips filenames down to the basename.  Please close this call and if you wish raise one on the [ESPlorer Issues page](/4refr0nt/ESPlorer/issues).  It's a different project.
