### ISSUE TITLE
Copy lua file (*.lua or *.lc) to ROM when flashing

### ISSUE THREAD

**Issue by vudangngoc** [nodemcu/nodemcu-firmware#559]
How can I create a folder and flash tool always copy file from this folder to ROM? I think this function is very helpful

**Comment by TerryE** [comment]
Whilst nodeMCU is based on eLua, there are some material differences. One is the eLua supports a ROMfs the content of which you initialise though the build process (and this can include lua or lc files).  
Whilst the ESP8266 does have a true ROM, this contains the Espressif boot loader, but for normal execution, the firmware is loaded from the on-module Flash memory, not ROM or eeROM.  nodeMCU uses SPIFFS to provide application access to available SPI Flash.  This is blank at build and there currently isn't a mechanism for pre installing files onto this, so this is a feature request rather than a bug.   My current work around is that I have a PC-based Lua script which writes a short provisioning bootstrap onto my ESP modules, so that when they are powered on for the first time, they download their initial config from an RPi on my home network.

**Comment by MarsTechHAN** [comment]
Yes, we can... But you need to add them when compilig the bin file at present. We are now trying to firgure out better way.

**Comment by TerryE** [comment]
@MarsTechHAN, Martin, surely the easiest method would be to have a Lua utility which runs on the host and takes a directory as an argument, plus the base `0x10000.bin` file and produces a separate `esptool` 0xNNNN.bin file with the SPIFFS image in it?  That way you can run the tool to produce the image without needing to do your own custom build.

**Comment by nodemcu** [comment]
pls checkout github.com/xlfe/spiffs

**Comment by vudangngoc** [comment]
https://github.com/xlfe/spiffs --> page not found

**Comment by nodemcu** [comment]
opps, sorry
https://github.com/xlfe/spiffy

**Comment by vudangngoc** [comment]
thank you for your information ^_^

**Comment by jmattsson** [comment]
Doh, wish I'd found that one before I wrote one myself. Ah well, here's another option for you: https://github.com/DiUS/spiffsimg

**Comment by kad** [comment]
spiffy looks good, however, is there easy way to get start address of SPIFS on running nodemcu device ?

**Comment by TerryE** [comment]
As well as [DiUS's spiffsimg](/DiUS/spiffsimg) this also links to the original [SPIFS project](/pellepl/spiffs).  I note that this has quite a few updates and fixes since nodeMCU regressed its changes.  It might be worth reviewing these to work out which should be merged into nodeMCU.

**Comment by jmattsson** [comment]
@TerryE The dev branch has SPIFFS 0.3.2 as of the other week merged in.

**Comment by TerryE** [comment]
@jmattsson, sorry missed this one.  :flushed:
