### ISSUE TITLE
sntp module

### ISSUE THREAD

**Issue by iMihael** [nodemcu/nodemcu-firmware#876]
Hello, I saw in documentation sntp module and tried to use it:
`sntp.sync('88.147.254.232', 
    function(sec,usec,server)
        print('sync', sec, usec, server)
    end
    )
`
but failed with error:
`attempt to index global 'sntp' (a nil value)`

I'm trying to search for sntp module in source code but I did not find any mention of it.
I'm using *0.9.6-dev_20150704* release of nodemcu firmware, builded from sources.

**Comment by nickandrew** [comment]
Please see #719.

**Comment by TerryE** [comment]
As Nick implies you need to be using a current build. The references give you the links.

**Comment by fulvous** [comment]
Hi bolsunovskyi you just need to rebuild your firmware enabling the sntp module. It seems it can be done on the cloud service, otherwise, if you are building by hand follow the next steps:

1) go to your firmware folder
2) edit the following file: app/include/user_modules.h
3) uncomment the following line:
#define LUA_USE_MODULES_SNTP
4) recompile with make
5) flash the new firmware.

I hope this helps
